version: '3'

services:

  db-madev:
    image: mysql:latest
    ports:
      - "9998:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin

      MYSQL_DATABASE: $MOODLE_DATABASE_NAME
      MYSQL_USER: $MOODLE_DATABASE_USER
      MYSQL_PASSWORD: $MOODLE_DATABASE_PASSWORD

    volumes:
      - ./moodle-database.sql:/docker-entrypoint-initdb.d/datadump.sql

  moodle:
    image: metrodataacademy/ma-moodle
    build: .
    env_file:
      - .env
    ports:
      - "9999:9999"
    depends_on:
      - db-madev
