version: '3'

services:
  db-madev:
    image: mysql:latest
    ports:
      - "9998:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin

      MYSQL_DATABASE: $MOODLE_DATABASE_NAME
      MYSQL_USER: $MOODLE_DATABASE_USER
      MYSQL_PASSWORD: $MOODLE_DATABASE_PASSWORD

    volumes:
      - ./moodle-database.sql:/docker-entrypoint-initdb.d/datadump.sql

  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'absujdbahsdjja.my.id'
      SITES: 'absujdbahsdjja.my.id=moodle:80'

  moodle:
    image: metrodataacademy/ma-moodle
    build: .
    env_file:
      - .env
    depends_on:
      - db-madev

volumes:
  ssl_data:
